[tool.poetry]
name = "cinemasite"
version = "0.1.0"
description = ""
authors = ["Marvelous-A <mogneto.r@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
