# Generated by Django 4.2.7 on 2024-03-22 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('category_discription', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('number_halls', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img_url', models.URLField()),
                ('discription', models.CharField(max_length=1000)),
                ('year', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=50)),
                ('duration', models.IntegerField(null=True)),
                ('category', models.ManyToManyField(to='card.category')),
                ('director', models.ManyToManyField(to='card.director')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(null=True)),
                ('cinema_name', models.CharField(max_length=50)),
                ('price', models.IntegerField(null=True)),
                ('format', models.CharField(max_length=5)),
                ('rows', models.IntegerField(null=True)),
                ('places', models.IntegerField(null=True)),
                ('getting_started', models.TimeField(null=True)),
                ('end_work', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brone_places', models.CharField(max_length=550)),
                ('resault_price', models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.cinema')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.film')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12)),
                ('birth_date', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('is_employer', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cinema',
            name='fk_cinema_halls',
            field=models.ManyToManyField(to='card.hall'),
        ),
    ]
