# Generated by Django 4.2.7 on 2023-11-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('img_url', models.CharField(max_length=800)),
                ('discription', models.CharField(max_length=1000)),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=10)),
            ],
        ),
    ]
