# Generated by Django 4.2.7 on 2024-03-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='end_work',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='getting_started',
            field=models.IntegerField(null=True),
        ),
    ]
