# Generated by Django 4.2.7 on 2024-01-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brone_places', models.CharField(max_length=550)),
                ('resault_price', models.CharField(max_length=550)),
            ],
        ),
    ]
