# Generated by Django 4.2.7 on 2024-04-03 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card', '0002_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.cinema')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.film')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.hall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
