# Generated by Django 4.2.7 on 2024-03-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_hall_end_work_hall_getting_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='end_work',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='getting_started',
            field=models.TimeField(null=True),
        ),
    ]
