# Generated by Django 4.2.7 on 2024-02-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
