# Generated by Django 4.2.7 on 2023-11-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_film_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
