# Generated by Django 4.2.7 on 2024-03-12 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_hall_end_work_alter_hall_getting_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='cinema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='card.cinema'),
            preserve_default=False,
        ),
    ]
