# Generated by Django 4.2.7 on 2024-04-03 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='screening',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='card.screening'),
            preserve_default=False,
        ),
    ]
