# Generated by Django 4.2.7 on 2024-02-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_film_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='film',
            name='category',
        ),
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(to='card.category'),
        ),
    ]
