# Generated by Django 4.2.7 on 2024-04-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_booking_screening'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='resault_price',
            field=models.IntegerField(null=True),
        ),
    ]
