# Generated by Django 4.2.7 on 2024-03-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_screening_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
