# Generated by Django 4.2.7 on 2023-11-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
