# Generated by Django 4.2.7 on 2024-02-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_remove_category_id_alter_category_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=50)),
                ('director_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(to='card.director'),
        ),
    ]
