# Generated by Django 4.2.7 on 2024-02-29 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_director_remove_film_director_film_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_user',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
