# Generated by Django 4.2.7 on 2024-03-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AddField(
            model_name='profile',
            name='is_employer',
            field=models.BooleanField(default=False),
        ),
    ]
