# Generated by Django 4.2.7 on 2024-02-29 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_profile_avatar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_user',
        ),
    ]
