# Generated by Django 4.2.7 on 2023-11-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_alter_film_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(max_length=60)),
                ('time', models.CharField(max_length=10)),
                ('price', models.IntegerField(null=True)),
                ('format', models.CharField(max_length=5)),
                ('rows', models.IntegerField(null=True)),
                ('places', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cinema',
            name='halls',
            field=models.CharField(default='sdsdf', max_length=1000),
        ),
    ]
