# Generated by Django 4.2.7 on 2023-11-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_hall_cinema_halls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='halls',
            field=models.CharField(max_length=1000),
        ),
    ]
