# Generated by Django 4.2.7 on 2024-03-07 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_remove_profile_avatar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='fk_cinema_halls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='card.hall'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hall',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
