# Generated by Django 4.2.7 on 2023-11-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_alter_cinema_halls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='halls',
            field=models.CharField(default='fdjdsjflskj', max_length=1000),
        ),
    ]
