# Generated by Django 4.2.7 on 2024-03-08 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_halls_films'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='halls_detal',
        ),
    ]
