# Generated by Django 4.2.7 on 2023-11-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_remove_cinema_halls_film_halls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='halls',
            field=models.CharField(max_length=1000),
        ),
    ]
