# Generated by Django 4.2.7 on 2023-11-14 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_alter_film_halls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='halls',
            new_name='cinemas_detals',
        ),
    ]
