# Generated by Django 4.2.7 on 2024-03-08 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_remove_hall_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='fk_cinema_halls',
        ),
        migrations.AddField(
            model_name='hall',
            name='fk_halls_cinema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='card.cinema'),
        ),
    ]
