# Generated by Django 4.2.7 on 2023-11-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_rename_halls_film_cinemas_detals'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='halls_detal',
            field=models.CharField(default='sufhsjd', max_length=1000),
        ),
    ]
