# Generated by Django 4.2.7 on 2023-11-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0014_cinema_halls_detal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='halls_detal',
            field=models.CharField(max_length=1000),
        ),
    ]
