# Generated by Django 4.2.7 on 2024-03-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0014_remove_cinema_fk_cinema_halls_hall_fk_halls_cinema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='cinema_name',
        ),
    ]
