# Generated by Django 4.2.7 on 2024-03-08 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0015_remove_hall_cinema_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halls_films',
            name='film_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.film'),
        ),
        migrations.AlterField(
            model_name='halls_films',
            name='hall_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.hall'),
        ),
    ]
