# Generated by Django 4.2.7 on 2024-03-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0016_alter_halls_films_film_id_alter_halls_films_hall_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='fk_cinema_halls',
            field=models.ManyToManyField(to='card.hall'),
        ),
    ]
