# Generated by Django 4.2.7 on 2024-03-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0017_cinema_fk_cinema_halls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='fk_halls_cinema',
        ),
        migrations.DeleteModel(
            name='Halls_Films',
        ),
    ]
